import type { Metadata } from 'next'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

const BaseLayout = ({ children }: { children: React.ReactNode }) => (
	<html lang="ja">
		<body>
			{/* Layout UI */}
			{/* Place children where you want to render a page or nested layout */}
			<Header />

			{/* main */}
			{children}

			<Footer />
		</body>
	</html>
)

export default BaseLayout
